version: "3.9"
services:
  caddy:
    build: ./../docker/caddy
    command: caddy run --config /etc/caddy/Caddyfile
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./sites:/etc/caddy/sites
      - ./coraza:/etc/coraza
      - caddy_admin_run:/run/caddy-admin
    ports: ["80", "8081:8081"]
  waf-admin:
    build: ..
    environment:
      - WAF_ADMIN_CONFIG=/app/config.yaml
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ./sites:/etc/caddy/sites
      - ./coraza:/etc/coraza
      - ./waf-admin-config.yaml:/app/config.yaml:ro
      - caddy_admin_run:/run/caddy-admin
    ports: ["8080:8080"]

volumes:
  caddy_admin_run:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
      o: "size=16m,uid=0,gid=0,mode=0777"
