apiVersion: v1
kind: ConfigMap
metadata: { name: {{ include "waf-admin.fullname" . }}-config }
data:
  config.yaml: |
    server: { bind: ":8080" }
    auth: { token: "${TOKEN}" }
    caddy:
      adminSocket: "{{ .Values.caddy.adminSocket }}"
      caddyfile:   "{{ .Values.caddy.caddyfile }}"
      sitesDir:    "{{ .Values.caddy.sitesDir }}"
      rulesRoot:   "{{ .Values.caddy.rulesRoot }}"
    backup:
      enabled: {{ .Values.backup.enabled }}
      daily: "{{ .Values.backup.daily }}"
      s3:
        endpoint: "{{ .Values.backup.s3.endpoint }}"
        region:   "{{ .Values.backup.s3.region }}"
        bucket:   "{{ .Values.backup.s3.bucket }}"
        accessKey: "${S3_ACCESS_KEY}"
        secretKey: "${S3_SECRET_KEY}"
        prefix:   "{{ .Values.backup.s3.prefix }}"
