apiVersion: apps/v1
kind: Deployment
metadata: { name: {{ include "waf-admin.fullname" . }} }
spec:
  replicas: 1
  selector: { matchLabels: { app: {{ include "waf-admin.name" . }} } }
  template:
    metadata: { labels: { app: {{ include "waf-admin.name" . }} } }
    spec:
      containers:
        - name: waf-admin
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: TOKEN
              valueFrom: { secretKeyRef: { name: {{ include "waf-admin.fullname" . }}-secrets, key: token } }
            - name: S3_ACCESS_KEY
              valueFrom: { secretKeyRef: { name: {{ include "waf-admin.fullname" . }}-secrets, key: s3_access_key } }
            - name: S3_SECRET_KEY
              valueFrom: { secretKeyRef: { name: {{ include "waf-admin.fullname" . }}-secrets, key: s3_secret_key } }
          volumeMounts:
            - { name: config, mountPath: /app/config.yaml, subPath: config.yaml, readOnly: true }
            - { name: sites,  mountPath: /etc/caddy/sites }
            - { name: rules,  mountPath: /etc/coraza }
            - { name: adminsock, mountPath: /run/caddy-admin }
      volumes:
        - name: config
          configMap: { name: {{ include "waf-admin.fullname" . }}-config }
        - name: sites
          persistentVolumeClaim: { claimName: {{ .Values.persistence.sitesClaimName }} }
        - name: rules
          persistentVolumeClaim: { claimName: {{ .Values.persistence.rulesClaimName }} }
        - name: adminsock
          emptyDir: { medium: "Memory" }
